import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Laila } from "next/font/google";
import { Space_Grotesk } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const laila = Laila({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-laila",
});
const space_grotesk = Space_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-space_grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${laila.className} ${space_grotesk.className}`}
      >
        {children}
      </body>
    </html>
  );
}
